version: '3'
services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    ports:
      - "5432:5432"
    networks:
      - traefik_net
    environment:
      POSTGRES_DB: invidious
      POSTGRES_PASSWORD: kemal
      POSTGRES_USER: kemal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 30s
      timeout: 5s
      retries: 2
  invidious:
    image: edgd1er/invidious
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        release: 1
        CRVERSION: 1.9.2
        disable_quic: 1
    restart: unless-stopped
    networks:
      - traefik_net
    ports:
      - "3001:3000"
    environment:
      TZ: Europe/Paris
      # Adapted from ./config/config.yml
      INVIDIOUS_CONFIG: |
        channel_threads: 1
        check_tables: true
        feed_threads: 1
        db:
          dbname: invidious
          user: kemal
          password: kemal
          host: postgres
          port: 5432
        check_tables: true
        hmac_key: "CHANGE_ME!!"
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/trending || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
volumes:
  postgresdata:
networks:
  traefik_net:
    external: true