name: Clean workflows
on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  clean_old_workflow:
    strategy:
      matrix:
        branch:
          - master
          - dev
    runs-on: ubuntu-latest
    env:
      DRY: false
    steps:
      - name: Delete failed workflows
        uses: dmvict/clean-workflow-runs@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          run_conclusions: |
            action_required
            cancelled
            failure
            neutral
            skipped
            stale
            timed_out
          save_period: 1
          save_min_runs_number: 0
          dry: ${{ env.DRY }}
          branch: ${{ matrix.branch }}

      - name: Delete workflow runs
        uses: dmvict/clean-workflow-runs@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          save_period: 30
          save_min_runs_number: 0
          dry: ${{ env.DRY }}
          branch: ${{ matrix.branch }}
